/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlycafe.Views;

import DAO.BillDAO;
import DAO.BillInFoDAO;
import DAO.CategoryDAO;
import DAO.DTO.Account;
import DAO.DTO.Categorys;
import DAO.DTO.Food;
import DAO.DTO.Table;
import DAO.FoodDAO;
import DAO.MenuDAO;
import DAO.TableDAO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Hashtable;
import java.util.Objects;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Lê H
 */
public class fTableManager extends javax.swing.JFrame {
    private int idTableClick = 0;
    private Account account ;
    /**
     * Creates new form fTableManager
     */
    public fTableManager(Account account) {
        this.account = account;
        initComponents();
        loadListTable();
        loadListCategory();
        loadListChangeTable();
    }
    private void loadListTable(){
        if(pnlShowTable.getComponentCount()> 0){
            pnlShowTable.removeAll();
            
            pnlShowTable.revalidate();
            pnlShowTable.repaint();
            
        }
        
        ArrayList<Table> listTable = TableDAO.instance().getAllListTable();
        
        for(Table x: listTable){
            JButton btn = new JButton(x.getName() + " \n" + x.getStatus());
            btn.setPreferredSize(new Dimension(Table.tableWidth, Table.tableHeight));
            
            if(!x.getStatus().equals("Trống")){
                btn.setBackground(Color.LIGHT_GRAY);
            }
            btn.addActionListener((e) -> {
                btnActionPerformed(e);
            });
            pnlShowTable.add(btn);
        }
    }
    private void loadListCategory(){
        ArrayList<Categorys> category = CategoryDAO.instence().getCategory();
        Collections.reverse(category);
        for(int i = 0; i< category.size();i++){
            listCategory.addItem(category.get(i).getNameCategory());
        }
    }
    
    private void loadListNameFood(int idCategory){
        if(listNameFood.getItemCount()>0){
            listNameFood.removeAllItems();
        }
        ArrayList<Food> ListNameFood = FoodDAO.instance().getListFoodByCategoryID(idCategory);
        for(int i = 0; i< ListNameFood.size(); i++){
            listNameFood.addItem(ListNameFood.get(i).getNameFood());
        }
    }
    private void loadListMenu(int idBill){
        tableListInFo.setModel(MenuDAO.instance().getListBillInFoBillID(idBill).getModel());
        double totalMoney = 0;
        int rowCount = tableListInFo.getRowCount();
        for(int i= 0; i< rowCount; i++){
            totalMoney +=(double) tableListInFo.getValueAt(i, 3);
        }
        tfTotalMoney.setText(Double.toString(totalMoney ));
    }
    private void loadListChangeTable() {
        ArrayList<Table> listTable = TableDAO.instance().getListTableStatus();
        
        for(int i = 0; i< listTable.size(); i++){
            listChuyenban.addItem(listTable.get(i).getName());
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlShowTable = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        listCategory = new javax.swing.JComboBox<>();
        listNameFood = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        countFood = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        scrollBillInfo = new javax.swing.JScrollPane();
        tableListInFo = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnChuyenBan = new javax.swing.JButton();
        btnGiamGia = new javax.swing.JButton();
        btnThanhToan = new javax.swing.JButton();
        listChuyenban = new javax.swing.JComboBox<>();
        GiamGia = new javax.swing.JSpinner();
        tfTotalMoney = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdmin = new javax.swing.JMenu();
        menuTrangQuanLy = new javax.swing.JMenuItem();
        menuInfo = new javax.swing.JMenu();
        menuInfoMenber = new javax.swing.JMenuItem();
        menuInfoDx = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý cafe");

        pnlShowTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlShowTable.setAlignmentX(1.0F);
        pnlShowTable.setAlignmentY(1.0F);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 15);
        flowLayout1.setAlignOnBaseline(true);
        pnlShowTable.setLayout(flowLayout1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        listCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listCategoryActionPerformed(evt);
            }
        });

        btnAdd.setText("Thêm món");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        countFood.setMaximumSize(new java.awt.Dimension(3, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(listCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listNameFood, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(countFood, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(listCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(listNameFood))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countFood, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableListInFo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên Món", "Giá", "Số lượng", "Tổng tiền"
            }
        ));
        scrollBillInfo.setViewportView(tableListInFo);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollBillInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollBillInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnChuyenBan.setText("Chuyển bàn");

        btnGiamGia.setText("Giảm giá");

        btnThanhToan.setText("Thanh toán");

        listChuyenban.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn bàn" }));

        tfTotalMoney.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tfTotalMoney.setForeground(new java.awt.Color(0, 51, 255));
        tfTotalMoney.setText("0");
        tfTotalMoney.setAlignmentX(1.0F);
        tfTotalMoney.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(listChuyenban, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChuyenBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(GiamGia)
                    .addComponent(btnGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTotalMoney)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(listChuyenban, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                            .addComponent(GiamGia)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfTotalMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuAdmin.setText("Admin");

        menuTrangQuanLy.setText("Truy cập trang quản lý'");
        menuTrangQuanLy.setToolTipText("");
        menuTrangQuanLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTrangQuanLyActionPerformed(evt);
            }
        });
        menuAdmin.add(menuTrangQuanLy);

        jMenuBar1.add(menuAdmin);

        menuInfo.setText("Thông tin tài khoản");

        menuInfoMenber.setText("Thông tin chi tiết");
        menuInfoMenber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuInfoMenberActionPerformed(evt);
            }
        });
        menuInfo.add(menuInfoMenber);

        menuInfoDx.setText("Đăng xuất");
        menuInfo.add(menuInfoDx);

        jMenuBar1.add(menuInfo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlShowTable, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlShowTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuInfoMenberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuInfoMenberActionPerformed
        // TODO add your handling code here:
        fAccount faAccount = new fAccount(this.account);
        faAccount.setVisible(true);
        
        //this.setVisible(true);
    }//GEN-LAST:event_menuInfoMenberActionPerformed

    private void menuTrangQuanLyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTrangQuanLyActionPerformed
        // TODO add your handling code here:
        fAdmin admin = new fAdmin();
        admin.setVisible(true);
    }//GEN-LAST:event_menuTrangQuanLyActionPerformed

    private void listCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listCategoryActionPerformed
        // TODO add your handling code here:
        int idCategory = listCategory.getSelectedIndex();
        
        loadListNameFood(idCategory);
        
    }//GEN-LAST:event_listCategoryActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        int idCategory   = listCategory.getSelectedIndex();
        int idFoodSelect = listNameFood.getSelectedIndex();
        ArrayList<Food> listFoodByCategory = FoodDAO.instance().getListFoodByCategoryID(idCategory);
        
        int idFood = listFoodByCategory.get(idFoodSelect).getId();
        
        int count = (int)countFood.getValue();
        
        int idBill = BillDAO.instance().GetUncheckBillIDByTableID(idTableClick);
        
        if(idCategory == 0 || idTableClick == 0 || (count <= 0 && MenuDAO.instance().getListBillInFoBillID(idBill).getRowCount() == 0))
            JOptionPane.showMessageDialog(rootPane, "Nhập lại lựa chọn!!");
        else{
            if(idBill == -1){
                BillDAO.instance().insertNewBillByIDTable(idTableClick);
                idBill = BillDAO.instance().getIDMaxBill();

            }
            BillInFoDAO.instance().insertBillInFo(idBill, idFood, count);
            TableDAO.instance().updateStatusTableByIDTable(idTableClick);

            loadListTable();

            loadListMenu(idBill);
        }
    }//GEN-LAST:event_btnAddActionPerformed
    
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {
        String[] tablenumber = evt.getActionCommand().split(" ");
        idTableClick = Integer.parseInt(tablenumber[1]);
        int idBill = BillDAO.instance().GetUncheckBillIDByTableID(idTableClick);
        
        loadListMenu(idBill);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner GiamGia;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChuyenBan;
    private javax.swing.JButton btnGiamGia;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JSpinner countFood;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JComboBox<String> listCategory;
    private javax.swing.JComboBox<String> listChuyenban;
    private javax.swing.JComboBox<String> listNameFood;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenu menuInfo;
    private javax.swing.JMenuItem menuInfoDx;
    private javax.swing.JMenuItem menuInfoMenber;
    private javax.swing.JMenuItem menuTrangQuanLy;
    private javax.swing.JPanel pnlShowTable;
    private javax.swing.JScrollPane scrollBillInfo;
    private javax.swing.JTable tableListInFo;
    private javax.swing.JTextField tfTotalMoney;
    // End of variables declaration//GEN-END:variables

    

    
}
