/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlysinhvien.Views;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.Hashtable;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.SimpleDoc;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.html.HTML;
import quanlysinhvien.model.QLSV_model;
import quanlysinhvien.model.TinhThanh;
import quanlysinhvien.model.thiSinh;

/**
 *
 * @author Lê H
 */
public class QLTS_Views extends javax.swing.JFrame {
    private QLSV_model lists;
    private DefaultTableModel table_model;
    private String path = "";
    private boolean flagSave = false;
    private thiSinh View_Info_ThiSinh;
    /**
     * Creates new form QLTS_Views
     */
    public QLTS_Views() {
        lists = new QLSV_model();
        initComponents();
        showComboData();
        groupSex();
        table_model = (DefaultTableModel) table_List.getModel();
        showResults(this.lists.getLists());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_filter = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        filter_Id = new javax.swing.JTextField();
        btn_filter = new javax.swing.JButton();
        filter_Add = new javax.swing.JComboBox<>();
        filter_Exit = new javax.swing.JButton();
        panel_Info = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        info_Id = new javax.swing.JTextField();
        info_Name = new javax.swing.JTextField();
        info_Birth = new javax.swing.JTextField();
        info_Add = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        info_Math = new javax.swing.JTextField();
        info_Physical = new javax.swing.JTextField();
        info_Chemistry = new javax.swing.JTextField();
        info_F = new javax.swing.JRadioButton();
        info_M = new javax.swing.JRadioButton();
        btn_Add = new javax.swing.JButton();
        btn_Delete = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Save = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        panel_List = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_List = new javax.swing.JTable();
        menu_About = new javax.swing.JMenuBar();
        menu_File = new javax.swing.JMenu();
        menu_Open = new javax.swing.JMenuItem();
        menu_FileOut = new javax.swing.JMenuItem();
        menu_Exit = new javax.swing.JMenuItem();
        About = new javax.swing.JMenu();
        menuAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_filter.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Student Filter"));

        jLabel1.setText("BirthPlace");

        jLabel3.setText("StudentID");

        btn_filter.setText("Filter");
        btn_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_filterActionPerformed(evt);
            }
        });

        filter_Add.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        filter_Exit.setText("Exit");
        filter_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filter_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_filterLayout = new javax.swing.GroupLayout(panel_filter);
        panel_filter.setLayout(panel_filterLayout);
        panel_filterLayout.setHorizontalGroup(
            panel_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filterLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filter_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filter_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filter_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );
        panel_filterLayout.setVerticalGroup(
            panel_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_filterLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panel_filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filter_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_filterLayout.createSequentialGroup()
                .addComponent(btn_filter, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filter_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_Info.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Student Information\n"));

        jLabel5.setText("ID");

        jLabel6.setText("Name");

        jLabel7.setText("Address");

        jLabel8.setText("Birth");

        info_Birth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                info_BirthFocusLost(evt);
            }
        });

        info_Add.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));

        jLabel9.setText("Sex");

        jLabel10.setText("Math");

        jLabel11.setText("Physical");

        jLabel12.setText("Chemistry");

        info_Math.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                info_MathFocusLost(evt);
            }
        });

        info_Physical.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                info_PhysicalFocusLost(evt);
            }
        });

        info_Chemistry.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                info_ChemistryFocusLost(evt);
            }
        });

        info_F.setText("Nam");

        info_M.setText("Nữ");

        javax.swing.GroupLayout panel_InfoLayout = new javax.swing.GroupLayout(panel_Info);
        panel_Info.setLayout(panel_InfoLayout);
        panel_InfoLayout.setHorizontalGroup(
            panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_InfoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_InfoLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info_Birth, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_InfoLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info_Add, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panel_InfoLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_InfoLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(info_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_InfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_InfoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info_Physical, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_Chemistry, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(info_Math, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_InfoLayout.createSequentialGroup()
                        .addComponent(info_F, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(info_M, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_InfoLayout.setVerticalGroup(
            panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_InfoLayout.createSequentialGroup()
                .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info_Id)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_InfoLayout.createSequentialGroup()
                        .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info_F, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(info_M, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(info_Math, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(info_Name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_InfoLayout.createSequentialGroup()
                        .addComponent(info_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(info_Chemistry, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(info_Birth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_InfoLayout.createSequentialGroup()
                        .addGroup(panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(info_Physical, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        btn_Add.setText("ADD");
        btn_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddActionPerformed(evt);
            }
        });

        btn_Delete.setText("DELETE");
        btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DeleteActionPerformed(evt);
            }
        });

        btn_Update.setText("UPDATE");
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Save.setText("SAVA");
        btn_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SaveActionPerformed(evt);
            }
        });

        btn_Exit.setText("EXIT");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        panel_List.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "List Student\n"));

        table_List.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "ID", "Nam", "Address", "BIrth", "Sex", "Math", "Physical", "Chemistry"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_List);

        javax.swing.GroupLayout panel_ListLayout = new javax.swing.GroupLayout(panel_List);
        panel_List.setLayout(panel_ListLayout);
        panel_ListLayout.setHorizontalGroup(
            panel_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_ListLayout.setVerticalGroup(
            panel_ListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu_File.setText("File");

        menu_Open.setText("Open file");
        menu_Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_OpenActionPerformed(evt);
            }
        });
        menu_File.add(menu_Open);

        menu_FileOut.setText("Print file");
        menu_FileOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_FileOutActionPerformed(evt);
            }
        });
        menu_File.add(menu_FileOut);

        menu_Exit.setText("Exit");
        menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_ExitActionPerformed(evt);
            }
        });
        menu_File.add(menu_Exit);

        menu_About.add(menu_File);

        About.setText("About");

        menuAbout.setText("About Me");
        About.add(menuAbout);

        menu_About.add(About);

        setJMenuBar(menu_About);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btn_Add)
                .addGap(48, 48, 48)
                .addComponent(btn_Delete)
                .addGap(50, 50, 50)
                .addComponent(btn_Update)
                .addGap(56, 56, 56)
                .addComponent(btn_Save)
                .addGap(39, 39, 39)
                .addComponent(btn_Exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panel_Info, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_filter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_List, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Info, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddActionPerformed
       /// them ds 
        if((this.View_Info_ThiSinh = makeTSToInfo())!= null){
            if(lists.findTS(View_Info_ThiSinh.getMaThiSinh()) != null)
                JOptionPane.showMessageDialog(menu_Open, "ID đã tồn tại sửa lại giúp con với!!");
            else{
                if(this.lists.addDAtabase(View_Info_ThiSinh)){
                    lists.insertTS(View_Info_ThiSinh);
                    showResult(View_Info_ThiSinh);
                    JOptionPane.showMessageDialog(menu_Open,"HaHa oke oke Nhập đúng\nTao thêm cho mi r đó");
                    info_Remove();
                }else{
                    JOptionPane.showMessageDialog(menu_Open, "kiểm tra laij kết nối ");
                }this.flagSave = false;
            } 
        }
        
    }//GEN-LAST:event_btn_AddActionPerformed


//check gias tri nhap vao
//  -------------------------------------------------    
    
    private void info_BirthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_info_BirthFocusLost
        // check dinh dang ngaysinh 
        SimpleDateFormat p = new SimpleDateFormat("dd/MM/yyyy");
        String tmp = info_Birth.getText();
        if(!tmp.equals(""))
            try{
                p.parse(tmp);
            }catch(Exception e){
                JOptionPane.showMessageDialog(menu_Open, "Sai định dạng (dd/mm/yyyy)\nMi có nhập đàng hoàng cho tau không thì bảo!!");
                info_Birth.setText("");
            }
    }//GEN-LAST:event_info_BirthFocusLost

    private void info_ChemistryFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_info_ChemistryFocusLost
        ///kiem tra dinh dang dau vao diem
        checkPoint(info_Chemistry);
    }//GEN-LAST:event_info_ChemistryFocusLost

    private void info_MathFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_info_MathFocusLost
        ///kiem tra dinh dang dau vao diem
        checkPoint(info_Math);
    }//GEN-LAST:event_info_MathFocusLost

    private void info_PhysicalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_info_PhysicalFocusLost
        ///kiem tra dinh dang dau vao diem
        checkPoint(info_Physical);
    }//GEN-LAST:event_info_PhysicalFocusLost

    private void btn_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_filterActionPerformed
        //btn loc
        
        String nametinh = filter_Add.getItemAt(filter_Add.getSelectedIndex());
        String ID = filter_Id.getText();
        
        if(ID.equals("")){
            if(nametinh.equals(""))
                JOptionPane.showMessageDialog(menu_Open, "Ngứa tay vừa thôi\nNhập thông tin vào rồi nhấn nút!!");
            else{
                showResults(lists.findTT(nametinh));
            }
        }else{
            removeResult();
            if((lists.findTS(ID))!= null)
                showResult(lists.findTS(ID));
        }
    }//GEN-LAST:event_btn_filterActionPerformed

    private void filter_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filter_ExitActionPerformed
        // TODO add your handling code here:
          filter_Add.setSelectedIndex(0);
          filter_Id.setText("");
          showResults(lists.getLists());
    }//GEN-LAST:event_filter_ExitActionPerformed

    private void menu_OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_OpenActionPerformed
        try {
            // TODO add your handling code here:
            path = JOptionPane.showInputDialog("Nhap vao đường dẫn file cần mở\nMi ơi!!\nSai tau thoát chương trình thì đừng trách", "Open File");
             new FileReader(path);
            
            lists.readFileTs(path);
            showResults(lists.getLists());
            JOptionPane.showMessageDialog(menu_Open, ("Tao đọc rồi đó\nThông tin file tau hiển thị trong bảng ơ."));
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(menu_Open, "Được cái đường dẫn nhập cũng không xong\nKiểm tra lại đường đẫn!!", "Loi rồi bây ơi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menu_OpenActionPerformed

    private void menu_FileOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_FileOutActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            String pathO = "";
            pathO = JOptionPane.showInputDialog("Nhap vao đường dẫn file cần xuat\n mi ơi!!", "Open File");
            File file = new File(pathO);
            if(!file.exists())
                file.createNewFile();
            lists.writeFileTs(pathO);
            JOptionPane.showMessageDialog(menu_Open, ("Ê tau xuất oke r á\nMở kì đường dẫn ni mà coi nề\n"+ path));
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(menu_Open, "Ối dời ơi\nSai đường dẫn file m ơi!!", "Lỗi rồi bây ơi",JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
             JOptionPane.showMessageDialog(menu_Open, "Ối dời ơi\nSai đường dẫn file m ơi!!", "Lỗi rồi bây ơi",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_menu_FileOutActionPerformed

    private void menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_ExitActionPerformed
        jFreamExit();
    }//GEN-LAST:event_menu_ExitActionPerformed

    private void btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DeleteActionPerformed
        // TODO add your handling code here:
//        lists.deleteTS((String) table_List.getValueAt(table_List.getSelectedRow(), 2));

        if(this.lists.removeDatabase(View_Info_ThiSinh)){
            this.lists.deleteTS(View_Info_ThiSinh);
            JOptionPane.showMessageDialog(menu_Open, "oke tao xoa cho may r do");
        }
        showResults(this.lists.getLists());
        info_Remove();
        this.flagSave = false;
    }//GEN-LAST:event_btn_DeleteActionPerformed

    private void table_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ListMouseClicked
      
        int row = table_List.getSelectedRow();
        String[] values = new String[10];
        
        for(int i = 1; i<= 8; i++){
            if(i>= 6){
                values[i-1] = Float.toString((float)table_List.getValueAt(row, i));
            }else{
                values[i-1] = (String) table_List.getValueAt(row, i);
            }
        }
        info_UpdateView(values[0], values[1], values[2], values[3], values[4], values[5], values[6], values[7]);
        this.View_Info_ThiSinh = makeTSToInfo();
    }//GEN-LAST:event_table_ListMouseClicked

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        // TODO add your handling code here:
        thiSinh tmp = View_Info_ThiSinh;
        if((View_Info_ThiSinh = makeTSToInfo())!= null){
            if(tmp.compareTS(View_Info_ThiSinh)){
                if(!tmp.getMaThiSinh().equals( View_Info_ThiSinh.getMaThiSinh()))
                    if(this.lists.removeDatabase(tmp) && this.lists.addDAtabase(View_Info_ThiSinh)){
                        this.lists.insertTS(View_Info_ThiSinh);
                        this.lists.deleteTS(tmp);
                    }else
                        JOptionPane.showMessageDialog(menu_Open, "loi ket noi sql là cái chắc lien hệ hải fix lại cho");
                else
                    this.lists.insertTS(View_Info_ThiSinh);
                showResults(lists.getLists());
                info_Remove();
                JOptionPane.showMessageDialog(menu_Open, "được r nghe đã cập nhật");
                this.flagSave = false;
            }else
                JOptionPane.showMessageDialog(menu_Open, "Liệu hồn nghe!!\nchưa thay đổi thông tin mà nhấn nút à");
            
        }
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SaveActionPerformed
        // TODO add your handling code here:
        if(!flagSave)
            this.lists.writeFileTs(path);
        JOptionPane.showMessageDialog(menu_Open, "An tâm tao lưu rồi đó\nHả dạ mày chưa");
        flagSave = true;
    }//GEN-LAST:event_btn_SaveActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        jFreamExit();
    }//GEN-LAST:event_btn_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JButton btn_Add;
    private javax.swing.JButton btn_Delete;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_Save;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_filter;
    private javax.swing.JComboBox<String> filter_Add;
    private javax.swing.JButton filter_Exit;
    private javax.swing.JTextField filter_Id;
    private javax.swing.JComboBox<String> info_Add;
    private javax.swing.JTextField info_Birth;
    private javax.swing.JTextField info_Chemistry;
    private javax.swing.JRadioButton info_F;
    private javax.swing.JTextField info_Id;
    private javax.swing.JRadioButton info_M;
    private javax.swing.JTextField info_Math;
    private javax.swing.JTextField info_Name;
    private javax.swing.JTextField info_Physical;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menuAbout;
    private javax.swing.JMenuBar menu_About;
    private javax.swing.JMenuItem menu_Exit;
    private javax.swing.JMenu menu_File;
    private javax.swing.JMenuItem menu_FileOut;
    private javax.swing.JMenuItem menu_Open;
    private javax.swing.JPanel panel_Info;
    private javax.swing.JPanel panel_List;
    private javax.swing.JPanel panel_filter;
    private javax.swing.JTable table_List;
    // End of variables declaration//GEN-END:variables

    private void showComboData() {
        ArrayList<TinhThanh> k = TinhThanh.getTinh();
        for(TinhThanh x: k){
            info_Add.addItem(x.getTenTinh());
            filter_Add.addItem(x.getTenTinh());
        }
    }

    private void groupSex() {
        ButtonGroup btn_groupSex = new ButtonGroup();
        btn_groupSex.add(info_F);
        btn_groupSex.add(info_M);
    }
    private void info_UpdateView(String maThiSinh, String tenThiSinh, String queQuan,String ngaysinh, String GioiTinh, String diem1, String diem2, String diem3) {
        info_Id.setText(maThiSinh);
        info_Name.setText(tenThiSinh);
        info_Add.setSelectedIndex(getIndexTinh(queQuan)+ 1);
        SimpleDateFormat p = new SimpleDateFormat("dd/MM/yyyy");
        info_Birth.setText(ngaysinh);
        info_Chemistry.setText(diem3);
        info_Math.setText(diem1);
        info_Physical.setText(diem3);
        if(GioiTinh.equals("F"))
            info_F.setSelected(true);
        else info_M.setSelected(true);
    }
    
    private void info_Remove() {
        info_Id.setText("");
        info_Name.setText("");
        info_Add.setSelectedIndex(0);
        info_Birth.setText("");
        info_Chemistry.setText("");
        info_Math.setText("");
        info_Physical.setText("");
        info_F.setSelected(false);
        info_M.setSelected(false);
    }
    int index_list = 1;
    
    private void showResults(Hashtable<String, thiSinh> ds) {
        setNo();
        removeResult();
        for(String x: ds.keySet()){
            thiSinh value = ds.get(x);
            showResult(value);
        }
    }
    private void setNo(){
        index_list = 1;
    }
    private void showResult(thiSinh value) {
        SimpleDateFormat p = new SimpleDateFormat("dd/MM/yyyy");
        table_model.addRow(new Object[]{
            index_list++, value.getMaThiSinh(), value.getTenThiSinh(), value.getQueQuan().getTenTinh()
                ,p.format(value.getNgaySinh()), value.getGioiTinh(), value.getDiem1(),
                value.getDiem2(), value.getDiem3()
            });
    }
    
    private void removeResult() {
        if(this.table_model != null)
            for(int i = table_model.getRowCount() -1; i>=0; i--){
                table_model.removeRow(i);
            }
    }
    
    private void checkPoint(JTextField point){
        if(!point.getText().equals(""))
            try{
                Float k = Float.parseFloat(point.getText());
                if(k< 0 || k >10){
                    JOptionPane.showMessageDialog(menu_Open, "Điểm phải thuộc đoạn 0 đến 10");
                    point.setText("");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(menu_Open, "Nhập sai định dạng điểm!!");
                point.setText("");
            }
    }
    private int getIndexTinh(String nameTinh){
        for(int i = 0; i<TinhThanh.getTinh().size(); i++){
            if(TinhThanh.getTinh().get(i).getTenTinh().equals(nameTinh))
                return i;
        }
        return -1;
    }
    private void saveAll(){
        if(!flagSave){
            int k = JOptionPane.showConfirmDialog(menu_Open, "M lưu chương trình k để t lưu hả thằng LOL", "Tao hỏi lại lần nữa", JOptionPane.YES_NO_OPTION);
                if(k == 0)
                    this.lists.writeFileTs(path);
        }
    }
    private void jFreamExit() {
        int t = JOptionPane.showConfirmDialog(menu_Open, "Bạn thực sự muốn thoát chương trình siu tuyệt vời này", "Thoat là bị điên đó.", JOptionPane.YES_NO_OPTION);
        if(t == 0)
            try {
                // TODO add your handling code here:
                saveAll();
                Thread.sleep(300);
            } catch (InterruptedException ex) {
                Logger.getLogger(QLTS_Views.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.dispose();
    }

    private thiSinh makeTSToInfo() {
        String maThiSinh, tenThiSinh, queQuan, GioiTinh, diem1, diem2, diem3, ngaySinh;
        maThiSinh = info_Id.getText().trim();
        this.lists.deleteTS(maThiSinh);
        tenThiSinh = info_Name.getText();
        
        int index = info_Add.getSelectedIndex();
        queQuan = info_Add.getItemAt(index);
        ngaySinh = info_Birth.getText();
        diem1 =info_Math.getText();
        diem2 =info_Physical.getText();
        diem3 =info_Chemistry.getText();
        GioiTinh = (info_F.isSelected())? "F": "M";
        if(maThiSinh.equals("") ||
            tenThiSinh.equals("")||
            queQuan.equals("")||
            ngaySinh.equals("")||
            GioiTinh.equals("")||
            diem1.equals("")||
            diem2.equals("")||
            diem3.equals("")){
            JOptionPane.showMessageDialog(menu_Open, "Trời ạ\nNhập đủ hộ con với làm ơn","Nhập sai lần nữa thử coi", JOptionPane.ERROR_MESSAGE);
             return null;
        }
        return new thiSinh(maThiSinh, tenThiSinh, queQuan, ngaySinh, GioiTinh, diem1, diem2, diem3);
    }


    

    
}
